import type { RawSheetAccount } from '../ledger/index.js';
export declare const testacct: RawSheetAccount;
export declare const testacctWithSettings: RawSheetAccount;
export declare const testacctAsset: {
    filename: string;
    name: string;
    lines: ({
        category: string;
        parcelid: string;
        purchaseValue?: undefined;
        taxCost?: undefined;
        taxPriorDepr?: undefined;
        taxCurrentDepr?: undefined;
        taxTotalDepr?: undefined;
        taxCurrentValue?: undefined;
        mktPriorValue?: undefined;
        mktCurrentValue?: undefined;
        mktCurrentDepr?: undefined;
        description?: undefined;
        purchaseDate?: undefined;
        taxAssetid?: undefined;
        taxDescription?: undefined;
        taxPriorValue?: undefined;
        saleDate?: undefined;
        saleValue?: undefined;
    } | {
        category: string;
        parcelid: string;
        purchaseValue: string;
        taxCost: string;
        taxPriorDepr: string;
        taxCurrentDepr: string;
        taxTotalDepr: string;
        taxCurrentValue: string;
        mktPriorValue: string;
        mktCurrentValue: string;
        mktCurrentDepr: string;
        description?: undefined;
        purchaseDate?: undefined;
        taxAssetid?: undefined;
        taxDescription?: undefined;
        taxPriorValue?: undefined;
        saleDate?: undefined;
        saleValue?: undefined;
    } | {
        category: string;
        parcelid: string;
        description: string;
        purchaseDate: string;
        purchaseValue: string;
        taxAssetid: string;
        taxDescription: string;
        taxTotalDepr: string;
        taxPriorValue: string;
        taxCurrentValue: string;
        mktPriorValue: string;
        mktCurrentValue: string;
        mktCurrentDepr: string;
        saleDate: string;
        saleValue: string;
        taxCost?: undefined;
        taxPriorDepr?: undefined;
        taxCurrentDepr?: undefined;
    })[];
};
